[[Pangomm]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49165f2d734848082b31a37447380b68429d3e97"
os = "macos"

    [[Pangomm.download]]
    sha256 = "53acb467108efbd1b79b525926bdff001f4e110d76a63c0a1c72a76c872f1d43"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.aarch64-apple-darwin-cxx03.tar.gz"
[[Pangomm]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "951b9ffc13a4842d7ab1eb3a325f84d331e22e72"
os = "macos"

    [[Pangomm.download]]
    sha256 = "8959c0ab3445e06112971e0526e22b25c3ed0301a5cfd9b0a5e671d930564394"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.aarch64-apple-darwin-cxx11.tar.gz"
[[Pangomm]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "563e80689c88ed5c184f1eceaf6710826a19703a"
libc = "glibc"
os = "linux"

    [[Pangomm.download]]
    sha256 = "f499d6ed32276080999426203bd0ad7c97f1dde15879dd310b511db45436bbee"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Pangomm]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b095070fea4e8020d22066a50f211fb863a7f8c"
libc = "glibc"
os = "linux"

    [[Pangomm.download]]
    sha256 = "63445129465c656e604f5fedd88c1c43f24d269cd24efd5b4f69bd046c52e761"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Pangomm]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8175b16b295eca24bdc861c4d61cb2710ff8b07a"
libc = "musl"
os = "linux"

    [[Pangomm.download]]
    sha256 = "9bb7cf7b13e9bc69251d859711be9e2575d63b50259e308f0f1931d07083426f"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.aarch64-linux-musl-cxx03.tar.gz"
[[Pangomm]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5d8f28fced8337d757a190eff03471c92a87183"
libc = "musl"
os = "linux"

    [[Pangomm.download]]
    sha256 = "b2d09f0cf1a750ad96d6015a620400effa482760197c0784bbc6a80ed7a36ef7"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.aarch64-linux-musl-cxx11.tar.gz"
[[Pangomm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c99762dadb7c9822060f592214ed4e3031d8b83"
libc = "glibc"
os = "linux"

    [[Pangomm.download]]
    sha256 = "f1bded2a3ac44677500eb31b0aecceca6b276ebcd6245f6e18d3aea10e870804"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Pangomm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31549023cec65a3a7b940f558b2db8c0cea7315d"
libc = "glibc"
os = "linux"

    [[Pangomm.download]]
    sha256 = "2a41d8551b9ed655519fd9df56ba2a39821361b02ae1eb1f8071d1f43be937e9"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Pangomm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "110b26162e10496d1ed5c37868ecee457916bd55"
libc = "musl"
os = "linux"

    [[Pangomm.download]]
    sha256 = "c0e1d859d55977516f72f52d8202cd3f51e32bb7dc6c211ac674c967438e7581"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Pangomm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9844f3cacfab1953b3eb868455752bfdbc8ae86"
libc = "musl"
os = "linux"

    [[Pangomm.download]]
    sha256 = "03fd107dc28509df223d4c32715d3f5ea95041a2ac33063895a4e3ea59db832a"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Pangomm]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81de09981969112ccab53de1d3a97a11663e3e2d"
libc = "glibc"
os = "linux"

    [[Pangomm.download]]
    sha256 = "dcbefa5a806a57e8a90db54c9e968d2e1d353bf941dcf8cb527c7780ecc825c5"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.i686-linux-gnu-cxx03.tar.gz"
[[Pangomm]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fbde7e560de425bc35db7801abaca6f9e8ada56"
libc = "glibc"
os = "linux"

    [[Pangomm.download]]
    sha256 = "00ab2a9b718ea594b358ac68922c53408988b0d9aef3206bc2686293a906a962"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.i686-linux-gnu-cxx11.tar.gz"
[[Pangomm]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "035dd9ae9bed8376db520b2bc08a29157e18b6c0"
libc = "musl"
os = "linux"

    [[Pangomm.download]]
    sha256 = "a182839fdecdd3c88d480fde9f6332d3fc0c8df3e288ecacf6ccecf5bf79d7b8"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.i686-linux-musl-cxx03.tar.gz"
[[Pangomm]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54e1af0d0bc7d900e507057da090fcbbc0cc2c19"
libc = "musl"
os = "linux"

    [[Pangomm.download]]
    sha256 = "632309d5df00be00669fa9f02d63155606c82f4a37414eddcf7ef62610b16f73"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.i686-linux-musl-cxx11.tar.gz"
[[Pangomm]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd0c26b6d06031d4a69ce6c5b01e0b5a372a04bf"
os = "windows"

    [[Pangomm.download]]
    sha256 = "cf10057a15c29e0eee27b86a063f21c287c2637c0d4a7b4467d2daa0638299fb"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.i686-w64-mingw32-cxx03.tar.gz"
[[Pangomm]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3135da81b01cb18db7e946d59f89c0138a87685f"
os = "windows"

    [[Pangomm.download]]
    sha256 = "7febba1640214081ffaea8309eeea0c7a12c3111967a337beed92d57debf12c8"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.i686-w64-mingw32-cxx11.tar.gz"
[[Pangomm]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23c6f5a66c333c5b4a4dcf33209eb99c301f868c"
libc = "glibc"
os = "linux"

    [[Pangomm.download]]
    sha256 = "4a094db0efb438728c097d024e30fa09d573f8c17251c5d149417d7f3523d478"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Pangomm]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6143843d5a10504a4d667fa92827502e638f3f0c"
libc = "glibc"
os = "linux"

    [[Pangomm.download]]
    sha256 = "d6dc57d1bbc363694564c02a32d9d358f4e3f20581512e96e826b1e1973d0d26"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Pangomm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba9b1a2b4e91f5658b9d02a214ac46fca49923a3"
os = "macos"

    [[Pangomm.download]]
    sha256 = "c7a1d1b9ab49d4300e1e147fb4f23f221827626bdbbf4b504e6ed3272d6cf963"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.x86_64-apple-darwin-cxx03.tar.gz"
[[Pangomm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70ddfc4b3c33654042056356b8920eb9c563adb2"
os = "macos"

    [[Pangomm.download]]
    sha256 = "7e30eea3af3e4c7edae148ac9b764be8537ebedbf7db0bb117406df9009b495c"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.x86_64-apple-darwin-cxx11.tar.gz"
[[Pangomm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03d0bc6092ccfb27e17ed5332dc5f19340aef75b"
libc = "glibc"
os = "linux"

    [[Pangomm.download]]
    sha256 = "53d2c65a377821365a5a9d3a7fca11212ca44c63c1f53a9557740635c03af534"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Pangomm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7afe00090c7317ff3c669112976fb58aca5c6c4"
libc = "glibc"
os = "linux"

    [[Pangomm.download]]
    sha256 = "ad46635d70b3abf53b03f1b4c50fd84bb29bb9a36671eb169b8f7bd72f3282f6"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Pangomm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "097a6236a0b78b5f2b974221290c0946c73c5175"
libc = "musl"
os = "linux"

    [[Pangomm.download]]
    sha256 = "2c9ac7082ce91cc622479a1e0c2bcf9d0836107632a6216cd10efb2ec49b25dc"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.x86_64-linux-musl-cxx03.tar.gz"
[[Pangomm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f79310cf2b1bc603eae80344eccc7bb553aa0714"
libc = "musl"
os = "linux"

    [[Pangomm.download]]
    sha256 = "0d0bbedca18fc3501d40cb317f7b13cd72cfb4ebcf3fd0ce8c7efcbcd12432e1"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.x86_64-linux-musl-cxx11.tar.gz"
[[Pangomm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6aebd62ae5e3b78e3deb0829965e03a14d76766f"
os = "freebsd"

    [[Pangomm.download]]
    sha256 = "e3c04c3c2830dae522e48ab6b1e565750042142925ed6f10ee2d2523c99636c7"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.x86_64-unknown-freebsd-cxx03.tar.gz"
[[Pangomm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c531eadead4f7d9177b9e4c4c7a3b918a356b36c"
os = "freebsd"

    [[Pangomm.download]]
    sha256 = "de1cfbb1692fb8b1b58c225e9d228afb81084eb5c0da9f07e9798b8ed318db63"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.x86_64-unknown-freebsd-cxx11.tar.gz"
[[Pangomm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e9c99074240faa7ae67590539ff24997772f74a"
os = "windows"

    [[Pangomm.download]]
    sha256 = "ed281bb1d9f064879245561b27ff9898c89040f0974c0ed440dd3ff2bc4640c6"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Pangomm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d81adab3e98129a3488bdf40da7dbfe35e6922d"
os = "windows"

    [[Pangomm.download]]
    sha256 = "5f4201e96e066bd388ddbd47306dda6329155eaf56d58efa632437619ecbcc3b"
    url = "https://github.com/JuliaBinaryWrappers/Pangomm_jll.jl/releases/download/Pangomm-v2.50.1+0/Pangomm.v2.50.1.x86_64-w64-mingw32-cxx11.tar.gz"
